# Generated by Django 4.2.13 on 2024-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=150)),
                ('user_mail', models.EmailField(default='', max_length=254)),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
    ]
