# Generated by Django 4.2.13 on 2024-05-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
